Added regression tests for raster2pgsql loader. Ticket is #1388
git-svn-id: http://svn.osgeo.org/postgis/trunk@9098 b70326c6-7e19-0410-871a-916f4a2858ee

diff --git a/regress/run_test b/regress/run_test
--- a/regress/run_test
+++ b/regress/run_test
@@ -8,6 +8,10 @@ DB=postgis_reg
 SHP2PGSQL=../loader/shp2pgsql
 PGSQL2SHP=../loader/pgsql2shp
 
+# raster2pgsql is relative to the place where this script
+# would be called: raster/test/regress
+RASTER2PGSQL=../../loader/raster2pgsql
+
 ###################################################
 #
 # Usage ./run_test <testname> [<testname>]
@@ -443,6 +447,107 @@ run_loader_test ()
 	return 0
 }
 
+#
+# This runs the loader once and checks the output of it.
+# It will NOT run if neither the expected SQL nor the expected
+# select results file exists, unless you pass true for the final
+# parameter.
+#
+# $1 - Description of this run of the loader, used for error messages.
+# $2 - Table name to load into.
+# $3 - The name of the file containing what the
+#      SQL generated by shp2pgsql should look like.
+# $4 - The name of the file containing the expected results of
+#      SELECT rast FROM _tblname should look like.
+# $5 - Command line options for raster2pgsql.
+# $6 - If you pass true, this will run the loader even if neither
+#      of the expected results files exists (though of course
+#      the results won't be compared with anything).
+#
+run_raster_loader_and_check_output()
+{
+	_description=$1
+	_tblname=$2
+	_expected_sql_file=$3
+	_expected_select_results_file=$4
+	_loader_options=$5
+	_run_always=$6
+	# ON_ERROR_STOP is used by psql to return non-0 on an error
+	_psql_opts="--no-psqlrc --variable ON_ERROR_STOP=true"
+
+	if [ -n "$_run_always" -o -r "$_expected_sql_file" -o -r "$_expected_select_results_file" ]; then
+		show_progress
+
+		# Produce the output SQL file.
+		${RASTER2PGSQL} $_loader_options -C -f the_rast ${TEST}.tif $_tblname \
+			> ${TMPDIR}/loader.out \
+			2> ${TMPDIR}/loader.err
+
+		if [ $? -gt 0 ]; then
+			fail " $_description: running raster2pgsql" "${TMPDIR}/loader.err"
+			return 1
+		fi
+
+		# Compare the output SQL file with the expected if there is one.
+		if [ -r $_expected_sql_file ]; then
+			show_progress
+			if diff "${TMPDIR}/loader.out" "$_expected_sql_file" > /dev/null; then
+				:
+			else
+				fail " $_description: actual SQL does not match expected.", \
+					"${TMPDIR}/loader.out"
+			fi
+		fi
+
+		# Run the loader SQL script.
+		show_progress
+		${PSQL} ${_psql_opts} -f ${TMPDIR}/loader.out "${DB}" > ${TMPDIR}/loader.err 2>&1
+		if [ $? -gt 0 ]; then
+			fail " $_description: running raster2pgsql output" "${TMPDIR}/loader.err"
+			return 1
+		fi
+
+		# Run the select script (if there is one)
+		if [ -r "${TEST}.select.sql" ]; then
+			if run_simple_test "${TEST}.select.sql" "$_expected_select_results_file" "$_description"; then
+				:
+			else
+				# That will have already called fail, so just return an error.
+				return 1
+			fi
+		fi
+	fi
+	return 0
+}
+
+#
+#  run_raster_loader_test 
+#
+#  Load a raster with different methods
+#
+#  raster input is ${TEST}.tif, expected output is {$TEST}.expected
+#
+run_raster_loader_test ()
+{
+	# See if there is a custom command-line options file
+	_custom_opts=""
+	if [ -r ${TEST}.opts ]; then
+		_custom_opts=`grep -v ^\s*# ${TEST}.opts`
+	fi
+
+	tblname="loadedrast"
+
+	if run_raster_loader_and_check_output "test" "${tblname}" "${TEST}.sql.expected" "${TEST}.select.expected" \
+		"$_custom_opts" "true"; then
+		:
+	else
+		return 1
+	fi
+	drop_table_if_exists "${tblname}" >> ${TMPDIR}/regress_log 2>&1
+
+	return 0
+}
+
 # Log an initialization error and optionally drop the db
 init_db_error ()
 {
@@ -536,7 +641,7 @@ if [ -z "$1" ]; then
 	echo " --nocreate   do not create the regression database on start" >&2
 	echo " --upgrade    source the upgrade scripts on start" >&2
 	echo " --nodrop     do not drop the regression database on exit" >&2
-	echo " --raster     load also topology extension" >&2
+	echo " --raster     load also raster extension" >&2
 	echo " --topology   load also topology extension" >&2
 	echo " --clean      cleanup test logs on exit" >&2
 	echo " --expect     save obtained output as expected" >&2
@@ -730,6 +835,12 @@ while [ -n "$1" ]; do
 	# .dbf files without a .shp.
 	if [ -r "${TEST}.dbf" ]; then
 		if run_loader_test; then
+			pass
+		fi
+	# Check .tif *before* .sql as loader test could
+	# create the .sql
+	elif [ -r "${TEST}.tif" ]; then
+		if run_raster_loader_test; then
 			pass
 		fi
 	elif [ -r "${TEST}.sql" ]; then
