Enable uninstall_topology.sql testing
git-svn-id: http://svn.osgeo.org/postgis/trunk@8560 b70326c6-7e19-0410-871a-916f4a2858ee

diff --git a/regress/run_test b/regress/run_test
--- a/regress/run_test
+++ b/regress/run_test
@@ -700,12 +700,21 @@ done
 # and nobody requested raster or topology
 # (until they have an uninstall script themself)
 if test x"$OPT_DROP" = "xyes" \
-     -a x"$OPT_WITH_TOPO" = "xno" \
      -a x"$object_count_pre" != "x"
 then # {
 
   start_test "uninstall"
   ok=yes
+
+  if test x"$OPT_WITH_TOPO" = "xyes"; then
+    ${PSQL} ${_psql_opts} -Xf ${REGDIR}/../topology/uninstall_topology.sql "${DB}" \
+           > ${TMPDIR}/uninstall.log 2> ${TMPDIR}/uninstall.err
+    if [ $? -gt 0 ]; then # {
+      fail "uninstall_topology.sql failed" "${TMPDIR}/uninstall.err"
+      ok=no
+    fi # }
+    show_progress # on to raster uninstall
+  fi
 
   if test x"$OPT_WITH_RASTER" = "xyes"; then
     ${PSQL} ${_psql_opts} -Xf ${REGDIR}/../raster/rt_pg/uninstall_rtpostgis.sql "${DB}" \
