Cleanly handle database creation error
git-svn-id: http://svn.osgeo.org/postgis/trunk@9740 b70326c6-7e19-0410-871a-916f4a2858ee

diff --git a/regress/run_test b/regress/run_test
--- a/regress/run_test
+++ b/regress/run_test
@@ -668,7 +668,11 @@ create_spatial ()
 {
 	echo "Creating spatial db ${DB} " 
 
-	createdb --encoding=UTF-8 --template=template0 --lc-collate="C" "${DB}" > ${TMPDIR}/regress_log
+	createdb --encoding=UTF-8 --template=template0 --lc-collate="C" "${DB}" > ${TMPDIR}/regress_log 2>&1 
+	if [ $? -gt 0 ]; then # {
+		fail "createdb failed" "${TMPDIR}/regress_log"
+		exit 1
+	fi # }
 	createlang plpgsql "${DB}" >> ${TMPDIR}/regress_log
 
 	# Count database objects before installing anything
