Fixes the following shp2pgsql issues: #229: A new "-r" command line parameter to specify a "from" SRID for reprojecting (the existing -s is the "to"). #779: -S now works for points, and -w is documented. #864: MULTIPOINT shapefiles with single-vertex points now correctly load with all MULTIPOINTs. #865: no longer crashes when both -g and -G are used.
git-svn-id: http://svn.osgeo.org/postgis/trunk@6922 b70326c6-7e19-0410-871a-916f4a2858ee

diff --git a/regress/run_test b/regress/run_test
--- a/regress/run_test
+++ b/regress/run_test
@@ -194,6 +194,127 @@ run_simple_test ()
 }
 
 #
+# This runs the loader once and checks the output of it.
+# It will NOT run if neither the expected SQL nor the expected
+# select results file exists, unless you pass true for the final
+# parameter.
+#
+# $1 - Description of this run of the loader, used for error messages.
+# $2 - Table name to load into.
+# $3 - The name of the file containing what the
+#      SQL generated by shp2pgsql should look like.
+# $4 - The name of the file containing the expected results of
+#      SELECT geom FROM _tblname should look like.
+# $5 - Command line options for shp2pgsql.
+# $6 - If you pass true, this will run the loader even if neither
+#      of the expected results files exists (though of course
+#      the results won't be compared with anything).
+#
+run_loader_and_check_output()
+{
+	_description=$1
+	_tblname=$2
+	_expected_sql_file=$3
+	_expected_select_results_file=$4
+	_loader_options=$5
+	_run_always=$6
+	# ON_ERROR_STOP is used by psql to return non-0 on an error
+	_psql_opts="--no-psqlrc --variable ON_ERROR_STOP=true"
+
+	if [ -n "$_run_always" -o -r "$_expected_sql_file" -o -r "$_expected_select_results_file" ]; then
+		show_progress
+		# Produce the output SQL file.
+		${SHP2PGSQL} $_loader_options -g the_geom ${TEST}.shp $_tblname \
+			> ${TMPDIR}/loader \
+			2> ${TMPDIR}/loader.err
+
+		if [ $? -gt 0 ]; then
+			fail " $_description: running shp2pgsql" "${TMPDIR}/loader.err"
+			return 1
+		fi
+
+		# Compare the output SQL file with the expected if there is one.
+		if [ -r $_expected_sql_file ]; then
+			show_progress
+			if diff "${TMPDIR}/loader" "$_expected_sql_file" > /dev/null; then
+				:
+			else
+				fail " $_description: actual SQL does not match expected.", \
+					"${TMPDIR}/loader"
+			fi
+		fi
+
+		# Blow away the test table if it already exists.
+		# MingW hack: use tr to strip off any trailing CR/LFs introduce by MingW which confuse expr
+		if [ `${PSQL} -t -A -c "SELECT count(*) FROM pg_tables WHERE tablename = '${_tblname}'" "${DB}" \
+				| tr -d '\r\n'` -gt 0 ]; then
+			show_progress
+			${PSQL} -c "DROP TABLE ${_tblname}" "${DB}" >> ${TMPDIR}/regress_log 2>&1
+		fi
+
+		# Run the loader SQL script.
+		show_progress
+		${PSQL} ${_psql_opts} -f ${TMPDIR}/loader "${DB}" > ${TMPDIR}/loader.err 2>&1
+		if [ $? -gt 0 ]; then
+			fail " $_description: running shp2pgsql output" "${TMPDIR}/loader.err"
+			return 1
+		fi
+
+		# Run the select script (if there is one)
+		if [ -r "${TEST}.select.sql" ]; then
+			if run_simple_test "${TEST}.select.sql" "$_expected_select_results_file" "$_description"; then
+				:
+			else
+				# That will have already called fail, so just return an error.
+				return 1
+			fi
+		fi
+	fi
+	return 0
+}
+
+#
+# This runs the dumper once and checks the output of it.
+# It will NOT run if the expected shp file does not exist, unless
+# you pass true for the final parameter.
+#
+# $1 - Description of this run of the dumper, used for error messages.
+# $2 - Table name to dump from.
+# $3 - If you pass true, this will run the loader even if neither
+#      of the expected results files exists (though of course
+#      the results won't be compared with anything).
+#
+run_dumper_and_check_output()
+{
+	_description=$1
+	_tblname=$2
+	_run_always=$3
+	_expected_shp_file="${TEST}.shp.expected"
+
+	if [ -n "$_run_always" -o -r "$_expected_shp_file" ]; then
+		show_progress
+		${PGSQL2SHP} -f ${TMPDIR}/dumper ${DB} "${_tblname}" > "${TMPDIR}/dumper.err" 2>&1
+		if [ $? -gt 0 ]; then
+			fail "$_description: dumping loaded table" "${TMPDIR}/dumper.err"
+			return 1
+		fi
+
+		# Compare with expected output if there is any.
+		if [ -r $_expected_shp_file ]; then
+			show_progress
+			if diff "${TMPDIR}"/dumper.shp "$_expected_shp_file" > /dev/null; then
+				:
+			else
+				ls -lL "${TMPDIR}"/dumper.shp "$_expected_shp_file" > "${TMPDIR}"/dumper.diff
+				fail "$_description: dumping loaded table" "${TMPDIR}/dumper.diff"
+				return 1
+			fi
+		fi
+	fi
+	return 0
+}
+
+#
 #  run_loader_test 
 #
 #  Load a shapefile with different methods, create a 'select *' SQL
@@ -203,208 +324,51 @@ run_simple_test ()
 #
 run_loader_test ()
 {
-	_tblname=loadedshp
-
-	# ON_ERROR_STOP is used by psql to return non-0 on an error
-	_psql_opts="--no-psqlrc --variable ON_ERROR_STOP=true"
-
-	#echo "SELECT * from ${_tblname}" > ${TEST}.sql
-
 	# See if there is a custom command-line options file
+	_custom_opts=""
 	if [ -r ${TEST}.opts ]; then
 		_custom_opts=`grep -v -m1 ^\s*# ${TEST}.opts`
 	fi
 
-
-	#
-	# Run in HEXWKB insert mode
-	#
-
-	show_progress
-
-	${SHP2PGSQL} $_custom_opts -g the_geom ${TEST}.shp $_tblname \
-		> ${TMPDIR}/loader \
-		2> ${TMPDIR}/loader.err
-
-	if [ $? -gt 0 ]; then
-		fail "running shp2pgsql" "${TMPDIR}/loader.err"
-		return 1
-
-	fi
-
-	show_progress
-
-	# MingW hack: use tr to strip off any trailing CR/LFs introduce by MingW which confuse expr
-	if [ `${PSQL} -t -A -c "SELECT count(*) FROM pg_tables WHERE tablename = '${_tblname}'" "${DB}" | tr -d '\r\n'` -gt 0 ]; then
-		${PSQL} -c "DROP TABLE ${_tblname}" "${DB}" >> ${TMPDIR}/regress_log 2>&1
-	fi
-
-	${PSQL} ${_psql_opts} -f ${TMPDIR}/loader "${DB}" > ${TMPDIR}/loader.err 2>&1
-	if [ $? -gt 0 ]; then
-		fail "sourcing shp2pgsql output" "${TMPDIR}/loader.err"
-		return 1
-	fi
-
-	if [ -f "${TEST}-wkb.sql" ]; then
-		if run_simple_test ${TEST}-wkb.sql ${TEST}-wkb.expected "wkb insert"; then
-			:
-		else
-			return 1
-		fi
-	fi
-
-
-	#
-	# Test in HEXWKB dump mode for all "normal" (no custom parameters) test cases.
-	# Some custom parameters can be incompatible with -D.
-	#
-	if [ -z "$_custom_opts" ]; then
-		show_progress
-
-		${SHP2PGSQL} -g the_geom -D ${TEST}.shp $_tblname \
-			> ${TMPDIR}/loader \
-			2> ${TMPDIR}/loader.err
-
-		if [ $? -gt 0 ]; then
-			fail "running shp2pgsql -D" "${TMPDIR}/loader.err"
-			return 1
-
-		fi
-
-		show_progress
-
-		${PSQL} -c "DROP table ${_tblname}" "${DB}" >> ${TMPDIR}/regress_log 2>&1
-		${PSQL} ${_psql_opts} -f ${TMPDIR}/loader "${DB}" > ${TMPDIR}/loader.err 2>&1
-		if [ $? -gt 0 ]; then
-			fail "sourcing shp2pgsql -D output" "${TMPDIR}/loader.err"
-			return 1
-		fi
-
-		if [ -f "${TEST}-wkb.sql" ]; then
-			if run_simple_test ${TEST}-wkb.sql ${TEST}-wkb.expected "wkb dump"; then
-				:
-			else
-				return 1
-			fi
-		fi
-	fi
-
-	###########################################################
-	#
-	# Dump and compare.
-	# Do this using WKB mode, as WKT is unable to reproduce
-	# M values
-	#
-
-	show_progress
-
-	${PGSQL2SHP} -f ${TMPDIR}/dumper ${DB} "${_tblname}" > "${TMPDIR}/dumper.err" 2>&1
-	if [ $? -gt 0 ]; then
-		fail "dumping loaded table" "${TMPDIR}/dumper.err"
-		return 1
-	fi
-
-	show_progress
-
-	if diff "${TMPDIR}"/dumper.shp "${TEST}".shp > /dev/null; then
+	# If we have some expected files to compare with, run in wkt mode.
+	if run_loader_and_check_output "wkt test" "loadedshp" "${TEST}-w.sql.expected" "${TEST}-w.select.expected" \
+		"-w $_custom_opts"; then
 		:
 	else
-		ls -lL "${TMPDIR}"/dumper.shp "${TEST}".shp > "${TMPDIR}"/dumper.diff
-		fail "dumping loaded table" "${TMPDIR}/dumper.diff"
 		return 1
 	fi
-
-# I'm not sure it's safe to compare indexes
-#	if diff "${TMPDIR}"/dumper.shx "${TEST}".shx; then
-#		:
-#	else
-#		ls -lL "${TMPDIR}"/dumper.shx "${TEST}".shx > "${TMPDIR}"/dumper.diff
-#		fail "dumping loaded table" "${TMPDIR}/dumper.diff"
-#		return 1
-#	fi
-
-# Change in attribute sizes would make this fail
-#	if diff "${TMPDIR}"/dumper.dbf "${TEST}".dbf; then
-#		:
-#	else
-#		ls -lL "${TMPDIR}"/dumper.dbf "${TEST}".dbf > "${TMPDIR}"/dumper.diff
-#		fail "dumping loaded table" "${TMPDIR}/dumper.diff"
-#		return 1
-#	fi
-
-
-	#
-	# End of dump and compare.
-	#
-	################################################
-
-	show_progress
-
-	${SHP2PGSQL} $_custom_opts -g the_geom -w ${TEST}.shp $_tblname \
-		> ${TMPDIR}/loader \
-		2> ${TMPDIR}/loader.err
-
-	if [ $? -gt 0 ]; then
-		fail "running shp2pgsql -w" "${TMPDIR}/loader.err"
+	# Always run in wkb ("normal") mode, even if there are no expected files to compare with.
+	if run_loader_and_check_output "wkb test" "loadedshp" "${TEST}.sql.expected" "${TEST}.select.expected" \
+		"$_custom_opts" "true"; then
+		:
+	else
 		return 1
 	fi
-
-	show_progress
-
-	${PSQL} -c "DROP table ${_tblname}" "${DB}" >> ${TMPDIR}/regress_log 2>&1
-	${PSQL} ${_psql_opts} -f ${TMPDIR}/loader "${DB}" > ${TMPDIR}/loader.err 2>&1
-	if [ $? -gt 0 ]; then
-		fail "sourcing shp2pgsql -w output" "${TMPDIR}/loader.err"
-		return 1
-	fi
-
-	if [ -f "${TEST}-wkt.sql" ]; then
-		if run_simple_test ${TEST}-wkt.sql ${TEST}-wkt.expected "wkt insert"; then
+	# Some custom parameters can be incompatible with -D.
+	if [ -z "$_custom_opts" ]; then
+		# If we have some expected files to compare with, run in wkt dump mode.
+		if run_loader_and_check_output "wkt dump test" "loadedshp" "${TEST}-wD.sql.expected" \
+			"${TEST}-w.select.expected" "-w -D"; then
+			:
+		else
+			return 1
+		fi
+		# If we have some expected files to compare with, run in wkb dump mode.
+		if run_loader_and_check_output "wkb dump test" "loadedshp" "${TEST}-D.sql.expected" \
+			"${TEST}.select.expected" "-D"; then
 			:
 		else
 			return 1
 		fi
 	fi
-
-	#
-	# Test in WKT dump mode for all "normal" (no custom parameters) test cases.
-	# Some custom parameters can be incompatible with -D.
-	#
-	if [ -z "$_custom_opts" ]; then
-
-		show_progress
-
-		${SHP2PGSQL} -g the_geom -D -w ${TEST}.shp $_tblname \
-			> ${TMPDIR}/loader \
-			2> ${TMPDIR}/loader.err
-
-		if [ $? -gt 0 ]; then
-			fail "running shp2pgsql -D -w" "${TMPDIR}/loader.err"
-			return 1
-
-		fi
-
-		show_progress
-
-		${PSQL} -c "DROP table ${_tblname}" "${DB}" >> ${TMPDIR}/regress_log 2>&1
-		${PSQL} ${_psql_opts} -f ${TMPDIR}/loader "${DB}" > ${TMPDIR}/loader.err 2>&1
-		if [ $? -gt 0 ]; then
-			fail "sourcing shp2pgsql -D -w output" "${TMPDIR}/loader.err"
-			return 1
-		fi
-
-		if [ -f "${TEST}-wkt.sql" ]; then
-			if run_simple_test ${TEST}-wkt.sql ${TEST}-wkt.expected "wkt dump"; then
-				:
-			else
-				return 1
-			fi
-		fi
+	# If we have some expected files to compare with, run the dumper and compare shape files.
+	if run_dumper_and_check_output "dumper test" "loadedshp"; then
+		:
+	else
+		return 1
 	fi
 
-	#rm ${TEST}.sql
-
-	return 0;
+	return 0
 }
 
 ###################################################
@@ -582,7 +546,7 @@ while [ -n "$1" ]; do
 		fi
         fi
 
-	# Check .shp *before* .sql as loader test would
+	# Check .shp *before* .sql as loader test could
 	# create the .sql
 	if [ -r "${TEST}.shp" ]; then
 		if run_loader_test; then
