Fixed error message on non-readable expected file
git-svn-id: http://svn.osgeo.org/postgis/trunk@2107 b70326c6-7e19-0410-871a-916f4a2858ee

diff --git a/regress/run_test b/regress/run_test
--- a/regress/run_test
+++ b/regress/run_test
@@ -33,7 +33,7 @@ if [ ! -r "${TEST}.sql" ]; then
 fi
 
 if [ ! -r "${TEST}_expected" ]; then
-	echo "Can't read ${TEST}.sql" >&2
+	echo "Can't read ${TEST}_expected" >&2
 	exit 1;
 fi
 
