Added -v switch to show differences inline
git-svn-id: http://svn.osgeo.org/postgis/trunk@2286 b70326c6-7e19-0410-871a-916f4a2858ee

diff --git a/regress/run_test b/regress/run_test
--- a/regress/run_test
+++ b/regress/run_test
@@ -23,7 +23,7 @@ if [ -z "$TMPDIR" ]; then
 fi
 
 if [ -z "$1" ]; then
-	echo "Usage: $0 <test> [<test>]" >&2
+	echo "Usage: $0 [-v] <test> [<test>]" >&2
 	exit 1;
 fi
 
@@ -69,11 +69,18 @@ echo
 echo "Running tests"
 echo
 
+VERBOSE=0
 RUN=0
 SKIP=0
 FAIL=0
 SUCCESS=0
 while [ -n "$1" ]; do
+
+	if test "$1" = "-v"; then
+		VERBOSE=1
+		shift
+		continue
+	fi
 
 	TEST="$1"; shift;
 
@@ -119,7 +126,16 @@ while [ -n "$1" ]; do
 		rm "${OUTFILE}" "${DIFFILE}" # we don't need these anymore
 	else
 		FAIL=`expr $FAIL + 1`
-		echo "Failed (diff ${DIFFILE})" # expected:'<'     obtained:'>'"
+		if test "$VERBOSE" -eq "1"; then
+			echo "Failed (diff ${DIFFILE})"
+			echo "-----------------------------------------------------------------------------"
+			echo "expected:'<'     obtained:'>'"
+			echo "-----------------------------------------------------------------------------"
+			cat ${DIFFILE}
+			echo "-----------------------------------------------------------------------------"
+		else
+			echo "Failed (diff ${DIFFILE})"
+		fi
 		rm "${OUTFILE}" # diff is enough
 	fi
 	RUN=`expr $RUN + 1`
